name: build

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check format
        run: cargo fmt --check

      - name: Build
        run: cargo build --release --verbose --locked

      - name: Run tests
        run: cargo test --release --verbose --locked
